title: Su Jiaji
logo: /images/profile.png
description: A PhD candidate from @ DSDS, NUS [[My CV]](./files/CV.pdf)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

orcid_url: https://orcid.org/0000-0003-3675-1407
GoogleScholar_url: https://scholar.google.com/citations?user=8r_W0EcAAAAJ
ResearchGate_url: https://www.researchgate.net/profile/Jiaji-Su 